#!/bin/sh
ROUTER=192.168.1.1
LOGIN=admin
PASSWD=admin

DEBUG=1
TMP_HEADER=/tmp/huawei-headers.$$

log() {
    echo "[huawei_router] $*" >&2
}

extract_from_xml() {
    echo "$1" | sed -n "s/.*<$2>\\([^<]\\+\\)<.*$/\\1/p"
}

prepare() {
    if [ -z "$COOKIE" ]; then
        log "Connecting"
        response=$(curl -s http://$ROUTER/api/webserver/SesTokInfo)
        COOKIE=$(extract_from_xml "$response" SesInfo)
        TOKEN=$(extract_from_xml "$response" TokInfo)
    fi
}

request() {
    prepare

    url=$1
    data=$2
    log "Requesting $url"

    curl_flags="-s"
    [ $DEBUG -eq 1 ] && curl_flags="$curl_flags -v"

    if [ -n "$data" ]; then
        [ $DEBUG -eq 1 ] && log "Posting: $data"

        rm -f "$TMP_HEADER"
        response=$(curl $curl_flags http://$ROUTER/$url \
            -D "$TMP_HEADER" \
            -H "__RequestVerificationToken: $TOKEN" \
            -H "Cookie: $COOKIE" \
            -H "Content-Length: ${#data}" \
            -H "X-Requested-With: XMLHttpRequest" \
            -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
            --data "$data")

        new_cookie=$(sed -n 's/^Set-Cookie:\([^;\n]*\).*$/\1/p' "$TMP_HEADER")
        if [ -n "$new_cookie" ]; then
            [ $DEBUG -eq 1 ] && log "Saving new session cookie"
            COOKIE="$new_cookie"
        fi
        new_token=$(sed -n 's/^__RequestVerificationTokentwo:\([^\r]*\).*$/\1/p' "$TMP_HEADER")
        if [ -n "$new_token" ]; then
            [ $DEBUG -eq 1 ] && log "Saving new token"
            TOKEN="$new_token"
        fi
        rm -f "$TMP_HEADER"
    else
        response=$(curl $curl_flags http://$ROUTER/$url \
            -H "Cookie: $COOKIE")
    fi

    [ $DEBUG -eq 1 ] && log "Response: $response"
}

is_logged_in() {
    request "api/user/state-login"
    username=$(extract_from_xml "$response" Username)
    state=$(extract_from_xml "$response" State)
    if [ "$state" = "0" ]; then
        log "Username $username, logged in"
    else
        if [ -z "$username" ]; then
            log "NOT logged in"
        else
            log "Username $username, NOT logged in"
        fi
    fi
}

status() {
    request "api/monitoring/status"
    echo "$response"
}

network() {
    request "api/net/current-plmn"
    echo "$response"
}

month_stats() {
    request "api/monitoring/month_statistics"
    echo "$response"
}

login() {
    prepare
    password=$(printf "$(printf "$PASSWD" | sha256sum |  cut -d ' ' -f 1)" | base64 -w 0)
    login_xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Username>$LOGIN</Username><Password>$(printf "$(printf "$LOGIN$password$TOKEN" | sha256sum | cut -d ' ' -f 1)" | base64 -w 0)</Password><password_type>4</password_type></request>"
    request api/user/login "$login_xml"

    ok=$(extract_from_xml "$response" response)
    if [ "$ok" != "OK" ]; then
        log "Couldn't log in"
        exit 2
    fi
}

unread_sms_count() {
    request "api/monitoring/check-notifications"
    extract_from_xml "$response" UnreadMessage
}

send_restart() {
    #
    # thanks to:
    # https://github.com/cmaion/huawei_router
    # https://github.com/mkorz/b618reboot/tree/master
    #
    send_reboot="<?xml version:"1.0" encoding="UTF-8"?><request><Control>1</Control></request>"
    request api/device/control "$send_reboot"
    
    ok=$(extract_from_xml "$response" response)
    if [ "$ok" != "OK" ]; then
        log "Error: send restart failed"
        exit 2
    else
        log "Ok: send restart successfully"
    fi
}

read_signal() {
    request "api/device/signal" "$xml_response"
    log "$response"
}

set_auto() {
    send_auto="<?xml version:'1.0' encoding='UTF-8'?><request><NetworkMode>00</NetworkMode><NetworkBand>3FFFFFFF</NetworkBand><LTEBand>7FFFFFFFFFFFFFFF</LTEBand></request>"
    request api/net/net-mode "$send_auto"
    log "$response"
}

set_4g() {
    send_4g="<?xml version:'1.0' encoding='UTF-8'?><request><NetworkMode>03</NetworkMode><NetworkBand>3FFFFFFF</NetworkBand><LTEBand>7FFFFFFFFFFFFFFF</LTEBand></request>"
    request api/net/net-mode "$send_4g"
    log "$response"
}

set_3g() {
    send_3g="<?xml version:'1.0' encoding='UTF-8'?><request><NetworkMode>02</NetworkMode><NetworkBand>3FFFFFFF</NetworkBand><LTEBand>7FFFFFFFFFFFFFFF</LTEBand></request>"
    request api/net/net-mode "$send_3g"
    log "$response"
}

send_sms() {
    phone=$1
    msg=$2
    sms_xml="<?xml version='1.0' encoding='UTF-8'?><request><Index>-1</Index><Phones><Phone>$phone</Phone></Phones><Sca></Sca><Content>$msg</Content><Length>${#msg}</Length><Reserved>1</Reserved><Date>$(date +"%Y-%m-%d %H:%M:%S")</Date></request>"
    request api/sms/send-sms "$sms_xml"

    ok=$(extract_from_xml "$response" response)
    if [ "$ok" != "OK" ]; then
        log "Couldn't send SMS"
        exit 2
    else
        log "SMS sent successfully"
    fi
}

read_sms() {
    request "api/sms/sms-count"
    count=$(extract_from_xml "$response" LocalInbox)
    log "$count message(s) in the inbox"

    if [ -n "$count" -a $count -gt 0 ]; then
        login
        sms_list_xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><PageIndex>1</PageIndex><ReadCount>$count</ReadCount><BoxType>1</BoxType><SortType>0</SortType><Ascending>0</Ascending><UnreadPreferred>0</UnreadPreferred></request>"
        request api/sms/sms-list "$sms_list_xml"
        echo $response
    fi
}

delete_sms() {
    index=$1
    sms_xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><Index>$index</Index></request>"
    request api/sms/delete-sms "$sms_xml"

    ok=$(extract_from_xml "$response" response)
    if [ "$ok" != "OK" ]; then
        log "Couldn't delete SMS $index"
        exit 2
    else
        log "SMS $index deleted successfully"
    fi
}

purge_sms_outbox() {
    request "api/sms/sms-count"
    count=$(extract_from_xml "$response" LocalOutbox)
    log "$count message(s) in the outbox"

    if [ -n "$count" -a $count -gt 0 ]; then
        login
        sms_list_xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><request><PageIndex>1</PageIndex><ReadCount>$count</ReadCount><BoxType>2</BoxType><SortType>0</SortType><Ascending>0</Ascending><UnreadPreferred>0</UnreadPreferred></request>"
        request api/sms/sms-list "$sms_list_xml"

        for index in $(extract_from_xml "$response" Index); do
            delete_sms $index
        done
    fi
}

usage() {
    exec 1>&2
    echo "Usage:"
    echo "  $0 [status|signal|set3g|set4g|setauto|network|restart|month_stats|unread_sms_count|purge_sms_outbox]"
    echo "  $0 read_sms"
    echo "  $0 send_sms <phone> <msg>"
    echo "  $0 delete_sms <sms_id>"
    echo "  $0 request <api/...>"
    echo "  $0 login_request <api/...>"
    exit 2
}

case $1 in
    request)
        shift
        request $1
        echo "$response"
        ;;
    login_request)
        shift
        login
        request $1
        echo "$response"
        ;;
    status)
        status
        ;;
    network)
        network
        ;;
    month_stats)
        month_stats
        ;;
    unread_sms_count)
        unread_sms_count
        ;;
    send_sms)
        shift
        login
        send_sms "$@"
        ;;
    read_sms)
        read_sms
        ;;
    delete_sms)
        shift
        login
        delete_sms $1
        ;;
    purge_sms_outbox)
        purge_sms_outbox
        ;;
    restart)
        shift
        login
        send_restart
        ;;
    signal)
        read_signal
        ;;
    set4g)
        shift
        login
        set_4g
        ;;
    set3g)
       shift
        login
        set_3g
        ;;
    setauto)
       shift
        login
        set_auto
        ;;
    *)
        usage
        ;;
esac
